<?php
class Chat extends Felin {
    private $_tauxDeCalin;
    private $_chiantitude;

    /**
     * Chat constructor.
     * @param $_tauxDeCalin
     * @param $_chiantitude
     */
    protected $_etatDeDomestication;
    protected $name;

    /**
     * Chat constructor.
     * @param $_tauxDeCalin
     * @param $_chiantitude
     * @param $_etatDeDomestication
     * @param $name
     */
    public function __construct($_tauxDeCalin, $_chiantitude, $_etatDeDomestication, $name, $ferocitude, $nourriture)
    {
        $this->_tauxDeCalin = $_tauxDeCalin;
        $this->_chiantitude = $_chiantitude;
        $this->_etatDeDomestication = $_etatDeDomestication;
        $this->name = $name;
    }


    /**
     * @return mixed
     */
    public function getTauxDeCalin()
    {
        return $this->_tauxDeCalin;
    }

    /**
     * @param mixed $tauxDeCalin
     */
    public function setTauxDeCalin($tauxDeCalin)
    {
        $this->_tauxDeCalin = $tauxDeCalin;
    }

    /**
     * @return mixed
     */
    public function getChiantitude()
    {
        return $this->_chiantitude;
    }

    /**
     * @param mixed $chiantitude
     */
    public function setChiantitude($chiantitude)
    {
        $this->_chiantitude = $chiantitude;
    }
    public function getMignonitude()
    {
        parent::getMignonitude(); // TODO: Change the autogenerated stub
        echo'je suis mignon fais moi des câlins';
    }


}